import { defineConfig } from 'astro/config';
import cloudflare from '@astrojs/cloudflare';
import react from '@astrojs/react';

const locales = ['en', 'ar', 'es', 'pt', 'id', 'fr', 'de', 'it', 'tr', 'ru', 'vi', 'th', 'ja', 'ko', 'pl', 'nl', 'ro', 'ms', 'fil', 'uk', 'cs', 'sv', 'hu', 'el', 'da', 'fi', 'no', 'bg', 'zh', 'hi'];
// https://astro.build/config
export default defineConfig({
    site: 'https://savetik-fast.xyz',
    trailingSlash: 'never',
    build: {
        format: 'file'
    },
    // Sitemaps are generated by src/pages/sitemap*.xml.ts. A single, explicit
    // URL set is easier for Search Console to process and lets us test every URL.
    integrations: [react()],
    i18n: {
        defaultLocale: 'en',
        locales: locales,
        routing: {
            prefixDefaultLocale: false
        }
    }
});
